### ISSUE TITLE
Free to add your best practice for any programming language

### ISSUE THREAD

**Issue by dereknguyen269** [dereknguyen269/programing-best-practices#20]

**Comment by utkr07** [comment]
I have solved many questions in C++ language. I can contribute good solutions of some amazing problems. Can you please assign me this task? @dereknguyen269

**Comment by Kdeveloper2000** [comment]
@dereknguyen269 Can you please assign it to me again? I want to add one more Good Quality Question.

**Comment by Lazar-Wolfe** [comment]
@dereknguyen269 Could you please assign it to me, I would like to contribute a question. Thanks

**Comment by dereknguyen269** [comment]
please submit PR with your best practice
