### ISSUE TITLE
C++ Solved programs

### ISSUE THREAD

**Issue by dereknguyen269** [dereknguyen269/programing-best-practices#21]

**Comment by dereknguyen269** [comment]
@utkr07

**Comment by Kdeveloper2000** [comment]
Hey, I would like to add one of the difficult questions. It was taken from Codeforces and contains many concepts.

**Comment by dereknguyen269** [comment]
> Hey, I would like to add one of the difficult questions. It was taken from Codeforces and contains many concepts.

it's ok
