### ISSUE TITLE
Feel free to submit your best practice for any programming language (Hacktoberfest 2023)

### ISSUE THREAD

**Issue by dereknguyen269** [dereknguyen269/programing-best-practices#47]
Feel free to submit your best practice for any programming language 🎉
Contributions are always welcome! 🚀 
Please read the [contribution guidelines](contributing.md) first.

**Comment by jfmartinz** [comment]
Hello @dereknguyen269, can I add this repo to the front end section?

repo link: https://github.com/ryanmcdermott/clean-code-javascript

**Comment by roniskywalker** [comment]
Hello [dereknguyen269](https://github.com/dereknguyen269), I want to work with this issue. Please assign me.

**Comment by dereknguyen269** [comment]
> Hello [dereknguyen269](https://github.com/dereknguyen269), I want to work with this issue. Please assign me.

Let do it. This issue for everyone ;)
